INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('r01', 'Cabernet Sauvignon');
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('r02', 'Sangiovese'); 
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('r03', 'Pinot Noir'); 
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('r04', 'Shiraz'); 
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('r05', 'Merlot'); 
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('w01', 'Chenin Blanc');
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('w02', 'Pinot Gris'); 
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('w03', 'Riesling'); 
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('w04', 'Sauvignon Blanc'); 
INSERT INTO wine_type(wine_type_code,wine_type_name) VALUES ('w05', 'Chardonnay'); 
commit;